/**
 * Cloudflare Worker entry point -- auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 */

import {
  handleApiRoute,
  matchPageRoute,
  renderPage,
  runMiddleware,
  vinextConfig,
} from "virtual:vinext-server-entry";
import {
  applyMiddlewareRequestHeaders,
  isExternalUrl,
  matchRedirect,
  matchRewrite,
  proxyExternalRequest,
  requestContextFromRequest,
  sanitizeDestination,
} from "vinext/config/config-matchers";
import type { ImageConfig } from "vinext/server/image-optimization";
import {
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
  handleImageOptimization,
  isImageOptimizationPath,
} from "vinext/server/image-optimization";
import {
  normalizeDefaultLocalePathname,
  stripI18nLocaleForApiRoute,
} from "vinext/server/pages-i18n";
import {
  applyConfigHeadersToHeaderRecord,
  cloneRequestWithHeaders,
  filterInternalHeaders,
  isOpenRedirectShaped,
  normalizeTrailingSlash,
} from "vinext/server/request-pipeline";
import { mergeRewriteQuery } from "vinext/utils/query";
import { notFoundStaticAssetResponse } from "../node_modules/vinext/dist/server/http-error-responses.js";
import {
  assetPrefixPathname,
  isNextStaticPath,
} from "../node_modules/vinext/dist/utils/asset-prefix.js";

interface Env {
  ASSETS: {
    fetch(request: Request): Promise<Response>;
  };
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Extract config values (embedded at build time in the server entry)
const basePath: string = vinextConfig?.basePath ?? "";
const assetPathPrefix: string = assetPrefixPathname(vinextConfig?.assetPrefix ?? "");
const trailingSlash: boolean = vinextConfig?.trailingSlash ?? false;
const i18nConfig = vinextConfig?.i18n ?? null;
const configRedirects = vinextConfig?.redirects ?? [];
const configRewrites = vinextConfig?.rewrites ?? { beforeFiles: [], afterFiles: [], fallback: [] };
const configHeaders = vinextConfig?.headers ?? [];
const imageConfig: ImageConfig | undefined = vinextConfig?.images
  ? {
      dangerouslyAllowSVG: vinextConfig.images.dangerouslyAllowSVG,
      dangerouslyAllowLocalIP: vinextConfig.images.dangerouslyAllowLocalIP,
      contentDispositionType: vinextConfig.images.contentDispositionType,
      contentSecurityPolicy: vinextConfig.images.contentSecurityPolicy,
    }
  : undefined;

function hasBasePath(pathname: string, basePath: string): boolean {
  if (!basePath) return false;
  return pathname === basePath || pathname.startsWith(`${basePath}/`);
}

function stripBasePath(pathname: string, basePath: string): string {
  if (!hasBasePath(pathname, basePath)) return pathname;
  return pathname.slice(basePath.length) || "/";
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    try {
      const url = new URL(request.url);
      let pathname = url.pathname;
      let urlWithQuery = pathname + url.search;

      // Block protocol-relative URL open redirects in all shapes:
      //   literal  //evil.com, /\\evil.com
      //   encoded  /%5Cevil.com, /%2F/evil.com
      // Browsers normalize backslash to forward slash, and they percent-decode
      // Location headers, so an encoded backslash in a downstream 308 redirect
      // would also navigate to the attacker's origin.
      if (isOpenRedirectShaped(pathname)) {
        return new Response("This page could not be found", { status: 404 });
      }

      // Invalid `_next/static/*` paths short-circuit with a plain-text 404
      // instead of falling through to renderPage (which would render the full
      // HTML 404 page with bootstrap scripts + CSS). Valid assets are served
      // by Cloudflare's ASSETS binding BEFORE the worker runs; only misses
      // reach this code. Matches Next.js (#1337):
      //   packages/next/src/server/lib/router-server.ts
      if (isNextStaticPath(pathname, basePath, assetPathPrefix)) {
        return notFoundStaticAssetResponse();
      }

      // Capture x-nextjs-data before filterInternalHeaders strips it -- the
      // middleware redirect protocol needs to know whether the inbound request
      // was a _next/data fetch to emit x-nextjs-redirect instead of a 3xx.
      const isDataRequest = request.headers.get("x-nextjs-data") === "1";

      // Strip internal headers from inbound requests so they cannot be
      // forged to influence routing or impersonate internal state.
      // Request.headers is immutable in Workers, so build a clean copy.
      {
        const filteredHeaders = filterInternalHeaders(request.headers);
        request = cloneRequestWithHeaders(request, filteredHeaders);
      }

      // ── 1. Strip basePath ─────────────────────────────────────────
      // Track basePath presence on the original request so the matcher
      // gating below can distinguish requests inside basePath (default
      // rules apply) from requests outside it (only opt-out rules apply).
      const hadBasePath = !basePath || hasBasePath(pathname, basePath);
      {
        const stripped = stripBasePath(pathname, basePath);
        if (stripped !== pathname) {
          urlWithQuery = stripped + url.search;
          pathname = stripped;
        }
      }
      const basePathState = { basePath, hadBasePath };

      // ── Image optimization via Cloudflare Images binding ──────────
      // Checked after basePath stripping so /<basePath>/_next/image works.
      if (isImageOptimizationPath(pathname)) {
        const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
        return handleImageOptimization(
          request,
          {
            fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
            transformImage: async (body, { width, format, quality }) => {
              const result = await env.IMAGES.input(body)
                .transform(width > 0 ? { width } : {})
                .output({ format, quality });
              return result.response();
            },
          },
          allowedWidths,
          imageConfig,
        );
      }

      // ── 2. Trailing slash normalization ────────────────────────────
      {
        const trailingSlashRedirect = normalizeTrailingSlash(
          pathname,
          basePath,
          trailingSlash,
          url.search,
        );
        if (trailingSlashRedirect) {
          return trailingSlashRedirect;
        }
      }

      // Build a request with the basePath-stripped URL for middleware and
      // downstream handlers. In Workers the incoming request URL still
      // contains basePath; prod-server constructs its webRequest from
      // the already-stripped URL, so we replicate that here.
      if (basePath) {
        const strippedUrl = new URL(request.url);
        strippedUrl.pathname = pathname;
        request = new Request(strippedUrl, request);
      }

      // Build request context for pre-middleware config matching. Redirects
      // run before middleware in Next.js. Header match conditions also use the
      // original request snapshot even though header merging happens later so
      // middleware response headers can still take precedence.
      // beforeFiles, afterFiles, and fallback rewrites run after middleware
      // (App Router order), so they use postMwReqCtx created after
      // x-middleware-request-* headers are unpacked into request.
      const reqCtx = requestContextFromRequest(request);

      // Default-locale path normalisation (issue #1336, item 4). Mirrors
      // Next.js's resolve-routes.ts: every request without a locale prefix
      // gets the (domain-aware) default locale prepended before config rule
      // matching so that locale-aware rules with :locale placeholders or
      // locale: false overrides still match default-locale URLs.
      const matchPathname = i18nConfig
        ? normalizeDefaultLocalePathname(pathname, i18nConfig, {
            hostname: url.hostname,
          })
        : pathname;

      // ── 3. Apply redirects from next.config.js ────────────────────
      if (configRedirects.length) {
        const redirect = matchRedirect(matchPathname, configRedirects, reqCtx, basePathState);
        if (redirect) {
          // Only prepend basePath when the request was actually under basePath.
          // Opt-out rules running on out-of-basepath requests must not receive
          // a basePath prefix.
          const dest = sanitizeDestination(
            basePath &&
              hadBasePath &&
              !isExternalUrl(redirect.destination) &&
              !hasBasePath(redirect.destination, basePath)
              ? `${basePath}${redirect.destination}`
              : redirect.destination,
          );
          return new Response(null, {
            status: redirect.permanent ? 308 : 307,
            headers: { Location: dest },
          });
        }
      }

      // ── 4. Run middleware ──────────────────────────────────────────
      let resolvedUrl = urlWithQuery;
      const middlewareHeaders: Record<string, string | string[]> = {};
      let middlewareRewriteStatus: number | undefined;
      if (typeof runMiddleware === "function") {
        const result = await runMiddleware(request, ctx, { isDataRequest });

        // Bubble up waitUntil promises (e.g. Clerk telemetry/session sync)
        if (result.waitUntilPromises?.length) {
          for (const p of result.waitUntilPromises) {
            ctx.waitUntil(p);
          }
        }

        if (!result.continue) {
          if (result.redirectUrl) {
            const redirectHeaders = new Headers({ Location: result.redirectUrl });
            if (result.responseHeaders) {
              for (const [key, value] of result.responseHeaders) {
                redirectHeaders.append(key, value);
              }
            }
            return new Response(null, {
              status: result.redirectStatus ?? 307,
              headers: redirectHeaders,
            });
          }
          if (result.response) {
            return result.response;
          }
        }

        // Collect middleware response headers to merge into final response.
        // Use an array for Set-Cookie to preserve multiple values.
        if (result.responseHeaders) {
          for (const [key, value] of result.responseHeaders) {
            if (key === "set-cookie") {
              const existing = middlewareHeaders[key];
              if (Array.isArray(existing)) {
                existing.push(value);
              } else if (existing) {
                middlewareHeaders[key] = [existing as string, value];
              } else {
                middlewareHeaders[key] = [value];
              }
            } else {
              middlewareHeaders[key] = value;
            }
          }
        }

        // Apply middleware rewrite
        if (result.rewriteUrl) {
          resolvedUrl = result.rewriteUrl;
        }

        // Apply custom status code from middleware rewrite
        middlewareRewriteStatus = result.rewriteStatus;
      }

      // Unpack x-middleware-request-* headers into the actual request and strip
      // all x-middleware-* internal signals. Rebuilds postMwReqCtx for use by
      // beforeFiles, afterFiles, and fallback config rules (which run after
      // middleware per the Next.js execution order).
      const { postMwReqCtx, request: postMwReq } = applyMiddlewareRequestHeaders(
        middlewareHeaders,
        request,
      );
      request = postMwReq;

      // Config header matching must keep using the original normalized pathname
      // even if middleware rewrites the downstream route/render target.
      let resolvedPathname = resolvedUrl.split("?")[0] ?? "/";

      // ── 5. Apply custom headers from next.config.js ───────────────
      // Config headers are additive for multi-value headers (Vary,
      // Set-Cookie) and override for everything else. Vary values are
      // comma-joined per HTTP spec. Set-Cookie values are accumulated
      // as arrays (RFC 6265 forbids comma-joining cookies).
      // Middleware headers take precedence: skip config keys already set
      // by middleware so middleware always wins for the same key.
      if (configHeaders.length) {
        applyConfigHeadersToHeaderRecord(middlewareHeaders, {
          configHeaders,
          pathname: matchPathname,
          requestContext: reqCtx,
          basePathState,
        });
      }

      if (isExternalUrl(resolvedUrl)) {
        const proxyResponse = await proxyExternalRequest(request, resolvedUrl);
        return mergeHeaders(proxyResponse, middlewareHeaders, undefined);
      }

      // Default-locale-normalised form of resolvedPathname for matching
      // against next.config.js rewrites (beforeFiles, afterFiles, fallback).
      const matchResolvedPathname = (p: string): string =>
        i18nConfig ? normalizeDefaultLocalePathname(p, i18nConfig, { hostname: url.hostname }) : p;

      // ── 6. Apply beforeFiles rewrites from next.config.js ─────────
      let configRewriteFired = false;
      if (configRewrites.beforeFiles?.length) {
        const rewritten = matchRewrite(
          matchResolvedPathname(resolvedPathname),
          configRewrites.beforeFiles,
          postMwReqCtx,
          basePathState,
        );
        if (rewritten) {
          if (isExternalUrl(rewritten)) {
            return proxyExternalRequest(request, rewritten);
          }
          // Preserve original query params across rewrites (Next.js parity).
          resolvedUrl = mergeRewriteQuery(resolvedUrl, rewritten);
          resolvedPathname = resolvedUrl.split("?")[0] ?? "/";
          configRewriteFired = true;
        }
      }

      // Reject out-of-basePath requests that no rule rewrote. See the
      // matching comment in prod-server.ts step 7b.
      if (basePath && !hadBasePath && !configRewriteFired) {
        return new Response("This page could not be found", {
          status: 404,
          headers: { "Content-Type": "text/html; charset=utf-8" },
        });
      }

      // ── 7. API routes ─────────────────────────────────────────────
      // Forward ctx so handlePagesApiRoute can wrap the user handler in
      // runWithExecutionContext, making ctx.waitUntil() reachable from
      // after() and other shims that schedule deferred work.
      //
      // Strip the i18n locale prefix before the /api/ check so
      // /fr/api/ok resolves to the pages/api/ok handler (Next.js
      // parity -- see base-server.ts's normalizeLocalePath call).
      const apiLookupUrl = stripI18nLocaleForApiRoute(resolvedUrl, vinextConfig?.i18n ?? null);
      const apiLookupPathname = apiLookupUrl.split("?")[0] ?? "/";
      if (apiLookupPathname.startsWith("/api/") || apiLookupPathname === "/api") {
        const response =
          typeof handleApiRoute === "function"
            ? await handleApiRoute(request, apiLookupUrl, ctx)
            : new Response("404 - API route not found", { status: 404 });
        return mergeHeaders(response, middlewareHeaders, middlewareRewriteStatus);
      }

      const pageMatch =
        typeof matchPageRoute === "function" ? matchPageRoute(resolvedPathname, request) : null;

      // ── 8. Apply afterFiles rewrites from next.config.js ──────────
      // These run after non-dynamic page routes but before dynamic routes.
      if ((!pageMatch || pageMatch.route.isDynamic) && configRewrites.afterFiles?.length) {
        const rewritten = matchRewrite(
          matchResolvedPathname(resolvedPathname),
          configRewrites.afterFiles,
          postMwReqCtx,
          basePathState,
        );
        if (rewritten) {
          if (isExternalUrl(rewritten)) {
            return proxyExternalRequest(request, rewritten);
          }
          resolvedUrl = mergeRewriteQuery(resolvedUrl, rewritten);
          resolvedPathname = resolvedUrl.split("?")[0] ?? "/";
        }
      }

      // ── 9. Page routes ────────────────────────────────────────────
      let response: Response | undefined;
      if (typeof renderPage === "function") {
        const renderPageMatch =
          typeof matchPageRoute === "function" ? matchPageRoute(resolvedPathname, request) : null;
        const shouldDeferErrorPageOnMiss =
          !isDataRequest && typeof matchPageRoute === "function" && !renderPageMatch;
        const initialRenderOptions = shouldDeferErrorPageOnMiss
          ? { renderErrorPageOnMiss: false }
          : undefined;
        response = await renderPage(
          request,
          resolvedUrl,
          null,
          ctx,
          undefined,
          initialRenderOptions,
        );

        // ── 10. Fallback rewrites (if SSR returned 404) ─────────────
        let matchedFallbackRewrite = false;
        if (
          response &&
          response.status === 404 &&
          shouldDeferErrorPageOnMiss &&
          configRewrites.fallback?.length
        ) {
          const fallbackRewrite = matchRewrite(
            matchResolvedPathname(resolvedPathname),
            configRewrites.fallback,
            postMwReqCtx,
            basePathState,
          );
          if (fallbackRewrite) {
            if (isExternalUrl(fallbackRewrite)) {
              return proxyExternalRequest(request, fallbackRewrite);
            }
            matchedFallbackRewrite = true;
            response = await renderPage(
              request,
              mergeRewriteQuery(resolvedUrl, fallbackRewrite),
              null,
              ctx,
            );
          }
        }
        if (
          response &&
          response.status === 404 &&
          shouldDeferErrorPageOnMiss &&
          !matchedFallbackRewrite
        ) {
          response = await renderPage(request, resolvedUrl, null, ctx);
        }
      }

      if (!response) {
        return new Response("This page could not be found", { status: 404 });
      }

      return mergeHeaders(response, middlewareHeaders, middlewareRewriteStatus);
    } catch (error) {
      console.error("[vinext] Worker error:", error);
      return new Response("Internal Server Error", { status: 500 });
    }
  },
};

/**
 * Merge middleware/config headers into a response.
 * Response headers take precedence over middleware headers for all headers
 * except Set-Cookie, which is additive (both middleware and response cookies
 * are preserved). Matches the behavior in prod-server.ts. Uses getSetCookie()
 * to preserve multiple Set-Cookie values. Keep this in sync with
 * prod-server.ts and server/worker-utils.ts.
 */
function mergeHeaders(
  response: Response,
  extraHeaders: Record<string, string | string[]>,
  statusOverride?: number,
): Response {
  const NO_BODY_RESPONSE_STATUSES = new Set([204, 205, 304]);
  function isVinextStreamedHtmlResponse(response: Response): boolean {
    return (
      (response as Response & { __vinextStreamedHtmlResponse?: boolean })
        .__vinextStreamedHtmlResponse === true
    );
  }
  function isContentLengthHeader(name: string): boolean {
    return name.toLowerCase() === "content-length";
  }
  function cancelResponseBody(response: Response): void {
    const body = response.body;
    if (!body || body.locked) return;
    void body.cancel().catch(() => {
      /* ignore cancellation failures on discarded bodies */
    });
  }

  const status = statusOverride ?? response.status;
  const merged = new Headers();
  // Middleware/config headers go in first (lower precedence)
  for (const [k, v] of Object.entries(extraHeaders)) {
    if (isContentLengthHeader(k)) continue;
    if (Array.isArray(v)) {
      for (const item of v) merged.append(k, item);
    } else {
      merged.set(k, v);
    }
  }
  // Response headers overlay them (higher precedence), except Set-Cookie
  // which is additive (both middleware and response cookies should be sent).
  response.headers.forEach((v, k) => {
    if (k === "set-cookie") return;
    merged.set(k, v);
  });
  const responseCookies = response.headers.getSetCookie?.() ?? [];
  for (const cookie of responseCookies) merged.append("set-cookie", cookie);

  const shouldDropBody = NO_BODY_RESPONSE_STATUSES.has(status);
  const shouldStripStreamLength =
    isVinextStreamedHtmlResponse(response) && merged.has("content-length");

  if (
    !Object.keys(extraHeaders).some((key) => !isContentLengthHeader(key)) &&
    statusOverride === undefined &&
    !shouldDropBody &&
    !shouldStripStreamLength
  ) {
    return response;
  }

  if (shouldDropBody) {
    cancelResponseBody(response);
    merged.delete("content-encoding");
    merged.delete("content-length");
    merged.delete("content-type");
    merged.delete("transfer-encoding");
    const responseInit: ResponseInit = {
      status,
      headers: merged,
    };
    if (status === response.status) {
      responseInit.statusText = response.statusText;
    }
    return new Response(null, responseInit);
  }

  if (shouldStripStreamLength) {
    merged.delete("content-length");
  }

  const responseInit: ResponseInit = {
    status,
    headers: merged,
  };
  if (status === response.status) {
    responseInit.statusText = response.statusText;
  }
  return new Response(response.body, responseInit);
}
